/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-05-07 11:50:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Files.JSP.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.database.conn.*;
import com.database.conn.DBConnection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.*;
import com.database.conn.*;
import com.database.conn.DBConnection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;

public final class AddVoterDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


		Connection con=DBConnection.getServerConnection();
		Statement st=null;
		ResultSet rs=null;
		String b_no=null;
		String b_ref_no=null;
		String b_location=null;
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Files/JSP/manager/Manager_content.jsp", Long.valueOf(1399381847497L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=\"text/javascript\">\r\n");
      out.write("  \twindow.history.forward();\r\n");
      out.write("   \tfunction noBack() { window.history.forward(); }\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"Stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/Files/CSS/Officer.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body background=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/index/bg.jpg\">\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<br><br>\t\t\t\t\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/index/logo-1.png\"><br><br>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/index/logo-2.png\">\r\n");
      out.write("\t\t</center>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t<div align=\"right\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" method=\"post\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/Files/JSP/manager/Managerhome.jsp\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/home.png\" height=\"30\" width=\"30\"></a>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/line.png\" height=\"30\" width=\"5\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/Files/JSP/manager/Manager_ChangePassword.jsp\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/changepwd.png\"\r\n");
      out.write("\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/changepwd-click.png'\"\r\n");
      out.write("   \t   \t \t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/changepwd.png'\"></a>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/line.png\" height=\"30\" width=\"5\">\t\t\r\n");
      out.write("\t\t\t<input type=\"image\" value=\"submit\" src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/logout.png\"\r\n");
      out.write("\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/logout-click.png'\"\r\n");
      out.write("   \t   \t \t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/logout.png'\">\t\r\n");
      out.write("\t\t\t&emsp;&emsp;\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\t");

		String manager_id=(String)request.getSession().getAttribute("x_manager_id");
		rs=Methods.ManagerBooth(manager_id);
		while(rs.next())
		{
			b_no=rs.getString(1);
			b_ref_no=rs.getString(2);
			b_location=rs.getString(3);
		}		
	
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"sidebar\">\r\n");
      out.write("\t\t<center><br><br>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/index/manager.png\" height=\"85\" width=\"85\"><br><br>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/Files/JSP/manager/VoterDetails.jsp\" >\t\r\n");
      out.write("   \t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/voterdetails.png\" \r\n");
      out.write("   \t\t\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/voterdetails-click.png'\"\r\n");
      out.write("   \t   \t \t\t\t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/voterdetails.png'\"/></a>\r\n");
      out.write("   \t   \t \t\t\t</td>\r\n");
      out.write("   \t   \t \t\t</tr>\r\n");
      out.write("   \t   \t \t\t<tr>\r\n");
      out.write("   \t   \t \t\t\t<td>\r\n");
      out.write("   \t   \t \t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/VotingProcess\" method=\"post\">\t\r\n");
      out.write("   \t\t\t\t\t\t\t<input type=\"image\" src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/information.png\" \r\n");
      out.write("   \t\t\t\t\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/information-click.png'\"\r\n");
      out.write("   \t   \t \t\t\t\t\t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/information.png'\"/>\r\n");
      out.write("   \t   \t \t\t\t\t</form>\r\n");
      out.write("   \t   \t \t\t\t</td>\r\n");
      out.write("   \t   \t \t\t</tr>\r\n");
      out.write("   \t   \t \t\t<tr>\r\n");
      out.write("   \t   \t \t\t\t<td>\r\n");
      out.write("   \t   \t \t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/Currentstatus\" method=\"post\">\t\r\n");
      out.write("   \t   \t \t\t\t\t\t<input type=\"hidden\" name=\"booth_no\" value=\"");
      out.print(b_no);
      out.write("\">\r\n");
      out.write("   \t\t\t\t\t\t\t<input type=\"image\" src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/currentstatus.png\" \r\n");
      out.write("   \t\t\t\t\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/currentstatus-click.png'\"\r\n");
      out.write("   \t   \t \t\t\t\t\t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/currentstatus.png'\"/>\r\n");
      out.write("   \t   \t \t\t\t\t</form>\r\n");
      out.write("   \t   \t \t\t\t</td>\r\n");
      out.write("   \t   \t \t\t</tr>\r\n");
      out.write("   \t   \t \t\t<tr>\r\n");
      out.write("   \t   \t \t\t\t<td>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/pollingprocess/index.jsp?booth_no=");
      out.print(b_no);
      out.write("&b_ref_no=");
      out.print(b_ref_no);
      out.write("&b_location=");
      out.print(b_location);
      out.write("\" >\t\r\n");
      out.write("   \t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/votingprocess.png\" \r\n");
      out.write("   \t\t\t\t\t\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/votingprocess-click.png'\"\r\n");
      out.write("   \t   \t \t\t\t\t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/votingprocess.png'\"/></a>   \t   \t \t\t\t\t\r\n");
      out.write("   \t   \t \t\t\t</td>\r\n");
      out.write("   \t   \t \t\t</tr>\t\r\n");
      out.write("   \t   \t \t</table>\r\n");
      out.write("\t\t</center>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>ADD VOTER DETAILS</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"Stylesheet\" type=\"text/css\" href=\"Officer.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/Files/JS/checkbox.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"content\"><center>\r\n");
      out.write("\t\t<div style=\"height:80px;width:790px;\">\r\n");
      out.write("\t\t<center><br><br>\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Manager/addvoterdetails.png\">\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
	String id_no="";
  			String name="";
  			String address="";
  			String sex="";
  			String age="";
 			String photo="";
 			String position="";
 			String vote_status="";
 			
 			//RETRIVING VALUES FROM SESSIONS
 			
 			HttpSession vses=request.getSession(true);
 			String temp_id_no=(String)vses.getAttribute("temp_id_no");
 			String temp_name=(String)vses.getAttribute("temp_name");
  			String temp_address=(String)vses.getAttribute("temp_address");
  			String temp_sex=(String)vses.getAttribute("temp_sex");
  			String temp_age=(String)vses.getAttribute("temp_age");
  			String temp_position=(String)vses.getAttribute("temp_position");
  			String temp_vote_status=(String)vses.getAttribute("temp_vote_status");
  			String temp_photo=request.getParameter("temp_photo");  			
  			if(temp_id_no==null)
  			{}else {id_no=temp_id_no;}
  			if(temp_name==null)
  			{}else {name=temp_name;}
 			if(temp_address==null)
  			{}else {address=temp_address;}
 			if(temp_sex==null)
  			{}else {sex=temp_sex;}
  			if(temp_age==null)
  			{}else {age=temp_age;}
  			if(temp_position==null)
  			{}else {position=temp_position;}
  			if(temp_vote_status==null)
  			{}else {vote_status=temp_vote_status;}
  			if(temp_photo==null)
  			{}else {photo=temp_photo;}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"height:280px;width:20px;float:right;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"height:280px;width:400px;float:right;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(temp_photo==null)
	  		{
      out.write("\r\n");
      out.write("\t  \t\t\t<center>\r\n");
      out.write("\t  \t\t\t\t<br><br><br><br><br><br>\r\n");
      out.write("\t\t\t\t\t<b>Select the image <br>to Preview</b>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t  \t");
	}else 
	  		{
	  			HttpSession sesn=request.getSession(true);
				sesn.setAttribute("temp_photo",temp_photo);
		
      out.write("\r\n");
      out.write("\t  \t<center><br><br><br><br>\t\r\n");
      out.write("\t  \t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/voters/");
      out.print(temp_photo);
      out.write("\" height=\"100\" width=\"100\">\r\n");
      out.write("\t  \t</center>\r\n");
      out.write("  \t  \t");
	}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/AddVoterDetail\" method=\"post\">\r\n");
      out.write("\t\t<div style=\"height:280px;width:360px;float:left;\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table style=\"font-family: cambria; font-weight: bold;\">\t\r\n");
      out.write("\t\t\t<tr height=\"30\">\t\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;VOTER ID</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"v_id_no\" required=\"requried\" value=\"");
      out.print(id_no);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;NAME</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"v_name\" required=\"requried\" value=\"");
      out.print(name);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;ADDRESS</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"v_address\" required=\"requried\" value=\"");
      out.print(address);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;AGE</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"v_age\" required=\"requried\" value=\"");
      out.print(age);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;SEX</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
	String[] v_sex ={"male", "female"};
			  		if(temp_sex==null)
			  		{
      out.write("\r\n");
      out.write("\t\t\t\t\t<select style=\"width:153px\" name=\"v_sex\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"male\">male</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"female\">female</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
	}
			  		else
			  		{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<select style=\"width:153px\" name=\"v_sex\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(temp_sex);
      out.write('"');
      out.write('>');
      out.print(temp_sex);
      out.write("</option>\r\n");
      out.write("\t\t\t\t");

						for(int i=0;i<v_sex.length;i++)
						{
							if(!v_sex[i].equals(temp_sex))
				      		{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(v_sex[i]);
      out.write('"');
      out.write('>');
      out.print(v_sex[i]);
      out.write("</option>\r\n");
      out.write("\t\t\t\t");
			}
						}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
	}
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;POSITION</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t");

				String[] v_position ={"available","dead","nontraceasble"};
			  	if(temp_position==null)
			  	{
      out.write("\r\n");
      out.write("\t\t\t\t\t<select style=\"width:153px\" name=\"v_position\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"available\">available</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"dead\">dead</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"nontraceasble\">nontraceasble</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t");
	}
				else
			  	{
      out.write("\r\n");
      out.write("\t\t\t\t\t<select style=\"width:153px\" name=\"v_position\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(temp_position);
      out.write('"');
      out.write('>');
      out.print(temp_position);
      out.write("</option>\r\n");
      out.write("\t\t\t");
		for(int i=0;i<v_position.length;i++)
					{
						if(!v_position[i].equals(temp_position))
				      	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(v_position[i]);
      out.write('"');
      out.write('>');
      out.print(v_position[i]);
      out.write("</option>\r\n");
      out.write("\t\t\t");
			}
					}
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t");
	}
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"30\">\r\n");
      out.write("\t\t\t\t<td>&emsp;&emsp;VOTE STATUS</td>\r\n");
      out.write("\t\t\t\t<td width=10%>:</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t");
	
				String[] v_vote_status ={"pending","polled"};
			  	if(temp_vote_status==null)
			  	{
      out.write("\r\n");
      out.write("\t\t\t\t\t<select style=\"width:153px\" name=\"v_vote_status\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"pending\">pending</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"polled\">polled</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t");
	}
			  	else
			  	{
      out.write("\r\n");
      out.write("\t\t\t\t\t<select style=\"width:153px\" name=\"v_vote_status\" required=\"requried\">\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(temp_vote_status);
      out.write('"');
      out.write('>');
      out.print(temp_vote_status);
      out.write("</option>\r\n");
      out.write("\t\t\t");

					for(int i=0;i<v_vote_status.length;i++)	
					{
						if(!v_vote_status[i].equals(temp_vote_status))
				      	{
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(v_vote_status[i]);
      out.write('"');
      out.write('>');
      out.print(v_vote_status[i]);
      out.write("</option>\r\n");
      out.write("\t\t\t");
			}
					}
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t");
	}
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if(temp_photo==null)
	{
      out.write("\r\n");
      out.write("\t\t<input type=\"image\" value=\"Submit\"src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/selectimage.png\" \r\n");
      out.write("  \t\t\t   onmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/selectimage-click.png'\"\r\n");
      out.write("   \t   \t\t   onmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/selectimage.png'\">\r\n");
      out.write("\t");
}
	else
	{
      out.write("\r\n");
      out.write("\t\t<input type=\"image\" value=\"Submit\"src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/add.png\" \r\n");
      out.write("  \t\t\t   onmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/add-click.png'\"\r\n");
      out.write("   \t   \t\t   onmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/add.png'\">\r\n");
	}
      out.write("\t</form>\t\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/Vot_add_cancel\" method=\"post\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"image\" value=\"Submit\" src=\"");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/cancel.png\"\r\n");
      out.write("\t\t\tonmouseover=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/cancel-click.png'\"\r\n");
      out.write("\t\t\tonmouseout=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Files/images/Officer/cancel.png'\">\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	String status=null;
	status=(String)request.getAttribute("Status");
	if(status==null)
	{
		
	}
	else
	{
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\talert(\"Sorry, Voter id already exists, Enter new Voter id\");\r\n");
      out.write("\t\t</script>\r\n");
	}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
